### ISSUE TITLE
Add support for inclusive range argument x...y

### ISSUE THREAD

**Issue by imp** [niconii/twiddle#4]
Current implementation overloads exclusive end range x..y meaning.
I may be more clear and suggestive to rather stick to the inclusive range syntax x...y.
The downside of course is that inclusive range are still nightly only

**Comment by niconii** [comment]
I do agree that the current situation with `.bits(7..0)`, `.replace(3..0, 0b1001)`, and so on isn't ideal.

That said, the future of `...` is [currently in question](https://github.com/rust-lang/rust/issues/28237#issuecomment-241437625), and I'd rather not make twiddle nightly-only anyway. Another alternative is going with `.bits(7, 0)` and `.replace(3, 0, 0b1001)`, but I don't really like the impact on readability there.

So, I guess I don't really have an answer for that at the moment. I may have to wait for the dust to settle around inclusive ranges before I decide what to do with this, though it looks like it'll be a while yet.

**Comment by niconii** [comment]
This is now finally fixed in release 1.0.0, which uses `..=`.

I've published it to crates.io, though 1.0.0 will be nightly-only until Rust 1.27.0, which stabilizes the `.start()` and `.end()` methods on inclusive ranges. As far as I know, it'll be usable on stable on June 21.
